// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Upload and Identify Image', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Upload and Identify Image', async function() {
    // Test name: Upload and Identify Image
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("http://localhost:5173/login")
    // 2 | setWindowSize | 1552x880 | 
    await driver.manage().window().setRect({ width: 1552, height: 880 })
    // 3 | type | css=.form-control:nth-child(2) > .input | test@example.us
    await driver.findElement(By.css(".form-control:nth-child(2) > .input")).sendKeys("test@example.us")
    // 4 | type | css=.form-control:nth-child(3) > .input | 000
    await driver.findElement(By.css(".form-control:nth-child(3) > .input")).sendKeys("000")
    // 5 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 6 | click | linkText=Image Recognition | 
    await driver.findElement(By.linkText("Image Recognition")).click()
    // 7 | click | css=.mb-4:nth-child(2) | 
    await driver.findElement(By.css(".mb-4:nth-child(2)")).click()
    // 8 | type | css=.hidden | C:\fakepath\plastic_water_bottle_bottom_014.jpg
    await driver.findElement(By.css(".hidden")).sendKeys("C:\\fakepath\\plastic_water_bottle_bottom_014.jpg")
    // 9 | click | css=.mt-4 | 
    await driver.findElement(By.css(".mt-4")).click()
    // 10 | click | css=.block:nth-child(2) | 
    await driver.findElement(By.css(".block:nth-child(2)")).click()
  })
})
